/**
 * AUTO-GENERATED by scripts/build-luxury-dispositions.mjs.
 * Do not edit by hand. Source of truth:
 *   docs/superpowers/specs/2026-04-14-luxury-teardown/url-dispositions.csv
 *
 * Generated: 2026-05-09T18:08:35.638Z
 * Kept (not redirected/gone): 1 URL(s), see CSV __KEEP__ rows
 */

export interface LuxuryRedirect { from: string; to: string; }

export const REDIRECTS: readonly LuxuryRedirect[] = [
  {
    "from": "/tools/property-tax-estimator/wa/king-county",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/wa/king-county/seattle",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/wa/king-county/bellevue",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/ca/santa-clara-county/san-jose",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/ca/san-mateo-county/san-mateo",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/ca/san-francisco-county/san-francisco",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/ca/marin-county",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/tools/property-tax-estimator/wa/king-county/sammamish",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/blog/home-equity-suburban-king-county-2026",
    "to": "/areas/washington"
  },
  {
    "from": "/blog/home-equity-greater-seattle-guide-2026",
    "to": "/areas/washington"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-tech-corridor-silicon-valley-2026",
    "to": "/areas/california"
  },
  {
    "from": "/tools/property-tax-estimator/wa/king-county/renton",
    "to": "/tools/property-tax-estimator"
  },
  {
    "from": "/areas/newport-beach-mortgage-broker",
    "to": "/blog/newport-beach-mortgage-guide-2026"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-bay-area-guide-2026",
    "to": "/blog/wholesale-mortgage-broker-california-guide-2026"
  },
  {
    "from": "/heloc-specialist-orange-county",
    "to": "/heloc-orange-county"
  },
  {
    "from": "/blog/home-equity-newport-beach-2026",
    "to": "/home-equity-guide"
  },
  {
    "from": "/blog/home-equity-bellevue-wa-2026",
    "to": "/blog/home-equity-seattle-eastside-wa-2026#bellevue"
  },
  {
    "from": "/articles/newport-beach-mortgage-guide-2026",
    "to": "/blog/newport-beach-mortgage-guide-2026"
  },
  {
    "from": "/blog/home-equity-laguna-beach-2026",
    "to": "/home-equity-guide"
  },
  {
    "from": "/blog/reverse-mortgage-bellevue-wa-2026",
    "to": "/blog/reverse-mortgage-seattle-eastside-wa-2026#bellevue"
  },
  {
    "from": "/blog/reverse-mortgage-la-beach-cities-2026",
    "to": "/blog/reverse-mortgage-la-south-bay-palos-verdes-guide-2026"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92625",
    "to": "/blog/wholesale-mortgage-broker-central-orange-county-2026#newport-beach"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92629",
    "to": "/blog/wholesale-mortgage-broker-south-orange-county-2026#dana-point"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92651",
    "to": "/blog/wholesale-mortgage-broker-south-orange-county-2026#laguna-beach"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92657",
    "to": "/blog/wholesale-mortgage-broker-central-orange-county-2026#newport-beach"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92660",
    "to": "/blog/wholesale-mortgage-broker-central-orange-county-2026#newport-beach"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92661",
    "to": "/blog/wholesale-mortgage-broker-central-orange-county-2026#newport-beach"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92663",
    "to": "/blog/wholesale-mortgage-broker-central-orange-county-2026#newport-beach"
  },
  {
    "from": "/blog/home-equity-clyde-hill-wa-2026",
    "to": "/blog/home-equity-seattle-eastside-wa-2026#mercer-medina"
  },
  {
    "from": "/blog/reverse-mortgage-clyde-hill-wa-2026",
    "to": "/blog/reverse-mortgage-seattle-eastside-wa-2026#ultra-luxury"
  },
  {
    "from": "/blog/reverse-mortgage-medina-wa-2026",
    "to": "/blog/reverse-mortgage-seattle-eastside-wa-2026#ultra-luxury"
  },
  {
    "from": "/blog/wholesale-mortgage-broker-92679",
    "to": "/blog/wholesale-mortgage-broker-south-orange-county-2026"
  }
];

export const GONE_410: readonly string[] = [
  "/blog/reverse-mortgage-south-sound-affluent-wa-2026",
  "/blog/wholesale-mortgage-broker-seattle-eastside-2026",
  "/tools/property-tax-estimator/ca/santa-clara-county/mountain-view",
  "/tools/property-tax-estimator/ca/santa-clara-county/palo-alto",
  "/tools/property-tax-estimator/ca/san-mateo-county/south-san-francisco",
  "/blog/reverse-mortgage-north-sound-islands-2026",
  "/blog/reverse-mortgage-greater-seattle-guide-2026",
  "/tools/property-tax-estimator/ca/marin-county/mill-valley",
  "/blog/home-equity-premium-east-bay-sf-2026",
  "/tools/property-tax-estimator/ca/san-mateo-county/daly-city",
  "/blog/reverse-mortgage-suburban-king-county-2026",
  "/blog/home-equity-bay-area-peninsula-guide-2026",
  "/blog/home-equity-urban-seattle-premium-2026",
  "/tools/property-tax-estimator/wa/king-county/kent",
  "/tools/property-tax-estimator/ca/santa-clara-county/los-gatos",
  "/blog/wholesale-mortgage-broker-ultra-luxury-eastside-wa-2026",
  "/blog/home-equity-south-sound-guide-2026",
  "/blog/home-equity-premium-silicon-valley-2026",
  "/blog/home-equity-ultra-luxury-eastside-wa-2026",
  "/blog/home-equity-north-sound-guide-2026",
  "/tools/property-tax-estimator/wa/king-county/burien",
  "/tools/property-tax-estimator/wa/king-county/kirkland",
  "/tools/property-tax-estimator/ca/marin-county/san-rafael",
  "/tools/property-tax-estimator/ca/los-angeles-county/rancho-palos-verdes",
  "/blog/wholesale-mortgage-broker-bay-area-peninsula-2026",
  "/blog/reverse-mortgage-premium-east-bay-sf-2026",
  "/blog/wholesale-mortgage-broker-coastal-sd-inland-premium-2026",
  "/blog/wholesale-mortgage-broker-premium-east-bay-sf-2026",
  "/blog/reverse-mortgage-seattle-eastside-guide-2026",
  "/blog/wholesale-mortgage-broker-premium-eastside-wa-2026",
  "/blog/reverse-mortgage-ultra-luxury-eastside-wa-2026",
  "/blog/home-equity-premium-eastside-wa-2026",
  "/blog/wholesale-mortgage-tech-corridor-eastside-wa-2026",
  "/blog/home-equity-south-sound-affluent-2026",
  "/blog/home-equity-coastal-sd-inland-premium-2026",
  "/blog/home-equity-tech-corridor-eastside-wa-2026",
  "/blog/wholesale-mortgage-broker-premium-silicon-valley-2026",
  "/blog/home-equity-tech-corridor-silicon-valley-2026",
  "/blog/reverse-mortgage-coastal-sd-inland-premium-2026",
  "/tools/property-tax-estimator/wa/king-county/kenmore",
  "/blog/home-equity-seattle-eastside-guide-2026",
  "/blog/home-equity-north-sound-islands-wa-2026",
  "/blog/home-equity-ultra-luxury-marin-2026",
  "/blog/reverse-mortgage-peninsula-ultra-luxury-2026",
  "/tools/property-tax-estimator/wa/king-county/seatac",
  "/blog/home-equity-peninsula-ultra-luxury-2026",
  "/blog/reverse-mortgage-tech-corridor-eastside-wa-2026",
  "/blog/reverse-mortgage-ultra-luxury-marin-2026",
  "/blog/reverse-mortgage-premium-silicon-valley-2026",
  "/tools/dscr-qualification-calculator/ca/marin-county",
  "/tools/bank-statement-loan-estimator/ca/san-francisco-county/san-francisco",
  "/tools/dscr-qualification-calculator/ca/san-mateo-county",
  "/blog/wholesale-mortgage-broker-greater-seattle-2026",
  "/blog/reverse-mortgage-bay-area-peninsula-guide-2026",
  "/tools/property-tax-estimator/wa/king-county/covington",
  "/blog/reverse-mortgage-tech-corridor-silicon-valley-2026",
  "/blog/wholesale-mortgage-broker-palos-verdes-peninsula-2026",
  "/blog/home-equity-palos-verdes-peninsula-2026",
  "/blog/wholesale-mortgage-broker-marin-county-2026",
  "/tools/dscr-rent-analyzer/ca/san-mateo-county/daly-city",
  "/blog/home-equity-la-south-bay-palos-verdes-guide-2026",
  "/blog/reverse-mortgage-seattle-eastside-wa-2026",
  "/blog/wholesale-mortgage-broker-suburban-king-county-2026",
  "/blog/wholesale-mortgage-broker-ultra-luxury-marin-2026",
  "/blog/wholesale-mortgage-broker-peninsula-ultra-luxury-2026",
  "/blog/reverse-mortgage-premium-eastside-wa-2026",
  "/tools/cash-out-limit-calculator/wa/king-county/seattle",
  "/tools/cash-out-limit-calculator/ca/marin-county",
  "/blog/reverse-mortgage-marin-county-guide-2026",
  "/tools/cash-out-limit-calculator/ca/santa-clara-county",
  "/tools/dscr-rent-analyzer/ca/san-francisco-county",
  "/tools/dscr-qualification-calculator/wa/king-county/auburn",
  "/tools/cash-out-limit-calculator/ca/san-mateo-county",
  "/tools/dscr-rent-analyzer/ca/san-mateo-county/foster-city",
  "/blog/reverse-mortgage-palos-verdes-peninsula-2026",
  "/blog/home-equity-seattle-eastside-wa-2026",
  "/tools/bank-statement-loan-estimator/ca/santa-clara-county/san-jose",
  "/blog/reverse-mortgage-la-south-bay-palos-verdes-guide-2026",
  "/tools/equity-comparison-calculator/ca/santa-clara-county/morgan-hill",
  "/tools/max-heloc-calculator/wa/king-county/bellevue",
  "/tools/max-heloc-calculator/ca/santa-clara-county",
  "/tools/cash-out-limit-calculator/ca/san-mateo-county/san-mateo",
  "/tools/bank-statement-loan-estimator/ca/san-mateo-county/redwood-city",
  "/tools/dscr-qualification-calculator/wa/king-county/maple-valley",
  "/blog/home-equity-marin-county-guide-2026",
  "/blog/reverse-mortgage-north-sound-guide-2026",
  "/tools/max-heloc-calculator/ca/santa-clara-county/gilroy",
  "/tools/cash-out-limit-calculator/ca/santa-clara-county/santa-clara",
  "/tools/dscr-qualification-calculator/ca/san-mateo-county/san-mateo",
  "/tools/dscr-rent-analyzer/ca/santa-clara-county/campbell",
  "/tools/dscr-qualification-calculator/ca/santa-clara-county/mountain-view",
  "/tools/equity-comparison-calculator/wa/king-county/seattle",
  "/tools/bank-statement-loan-estimator/wa/king-county/burien",
  "/tools/equity-comparison-calculator/ca/santa-clara-county",
  "/tools/cash-out-limit-calculator/ca/santa-clara-county/mountain-view",
  "/tools/dscr-rent-analyzer/wa/king-county/issaquah",
  "/tools/max-heloc-calculator/wa/king-county/maple-valley",
  "/tools/dscr-qualification-calculator/ca/santa-clara-county/milpitas",
  "/blog/wholesale-mortgage-broker-la-south-bay-palos-verdes-2026",
  "/tools/dscr-rent-analyzer/wa/king-county/auburn",
  "/tools/equity-comparison-calculator/ca/santa-clara-county/milpitas",
  "/tools/cash-out-limit-calculator/ca/marin-county/mill-valley",
  "/blog/reverse-mortgage-south-sound-guide-2026",
  "/tools/cash-out-limit-calculator/wa/king-county/kent",
  "/tools/dscr-qualification-calculator/ca/san-francisco-county",
  "/tools/max-heloc-calculator/wa/king-county/mercer-island",
  "/tools/cash-out-limit-calculator/ca/santa-clara-county/palo-alto",
  "/tools/max-heloc-calculator/ca/santa-clara-county/milpitas",
  "/tools/dscr-qualification-calculator/wa/king-county/sammamish",
  "/tools/dscr-rent-analyzer/ca/marin-county/san-rafael",
  "/blog/reverse-mortgage-urban-seattle-premium-2026",
  "/tools/cash-out-limit-calculator/wa/king-county/kirkland",
  "/tools/cash-out-limit-calculator/wa/king-county",
  "/tools/dscr-qualification-calculator/ca/marin-county/mill-valley",
  "/tools/dscr-rent-analyzer/ca/san-mateo-county/san-mateo",
  "/tools/max-heloc-calculator/ca/san-mateo-county",
  "/tools/equity-comparison-calculator/wa/king-county/redmond",
  "/tools/equity-comparison-calculator/wa/king-county/renton",
  "/tools/dscr-qualification-calculator/wa/king-county/kent",
  "/tools/equity-comparison-calculator/ca/santa-clara-county/los-gatos",
  "/blog/home-equity-palos-verdes-2026",
  "/tools/max-heloc-calculator/ca/santa-clara-county/palo-alto",
  "/tools/dscr-rent-analyzer/ca/los-angeles-county/rancho-palos-verdes",
  "/tools/dscr-qualification-calculator/ca/marin-county/san-rafael",
  "/tools/dscr-rent-analyzer/wa/king-county/kenmore",
  "/tools/dscr-rent-analyzer/wa/king-county/kent",
  "/tools/equity-comparison-calculator/ca/santa-clara-county/mountain-view",
  "/tools/dscr-qualification-calculator/wa/king-county/seattle",
  "/tools/dscr-qualification-calculator/ca/san-mateo-county/redwood-city",
  "/tools/equity-comparison-calculator/wa/king-county/auburn",
  "/tools/dscr-qualification-calculator/wa/king-county/bellevue",
  "/tools/bank-statement-loan-estimator/ca/santa-clara-county/morgan-hill",
  "/tools/bank-statement-loan-estimator/wa/king-county/seattle",
  "/tools/equity-comparison-calculator/ca/santa-clara-county/san-jose",
  "/luxury-markets",
  "/luxury-markets/waterfront-homes-mortgage-broker",
  "/luxury-markets/ultra-luxury-estates-mortgage-broker",
  "/luxury-markets/golf-course-homes-mortgage-broker",
  "/areas/newport-beach-neighborhoods/balboa-island-mortgage-broker",
  "/areas/newport-beach-neighborhoods/lido-isle-mortgage-broker",
  "/areas/newport-beach-neighborhoods/newport-coast-mortgage-broker",
  "/areas/newport-beach-neighborhoods/corona-del-mar-mortgage-broker",
  "/blog/home-equity-affluent-marin-2026",
  "/blog/home-equity-ca-pv-a-2026",
  "/blog/home-equity-ca-pv-b-2026",
  "/blog/home-equity-foothill-luxury-2026",
  "/blog/home-equity-la-westside-luxury-2026",
  "/blog/home-equity-santa-barbara-luxury-2026",
  "/blog/home-equity-western-la-luxury-2026",
  "/blog/newport-coast-mortgage-guide-2026",
  "/blog/palos-verdes-cash-out-refinance-2026",
  "/blog/reverse-mortgage-affluent-marin-2026",
  "/blog/reverse-mortgage-foothill-luxury-2026",
  "/blog/reverse-mortgage-la-westside-luxury-2026",
  "/blog/reverse-mortgage-palos-verdes-2026",
  "/blog/reverse-mortgage-santa-barbara-luxury-2026",
  "/blog/reverse-mortgage-western-la-luxury-2026",
  "/blog/wholesale-mortgage-92657-newport-coast-2026",
  "/blog/wholesale-mortgage-92662-balboa-island-2026",
  "/blog/wholesale-mortgage-92663-newport-peninsula-2026",
  "/blog/wholesale-mortgage-broker-affluent-marin-2026",
  "/blog/wholesale-mortgage-broker-ca-pv-a-2026",
  "/blog/wholesale-mortgage-broker-ca-pv-b-2026",
  "/blog/wholesale-mortgage-broker-foothill-luxury-2026",
  "/blog/wholesale-mortgage-broker-la-westside-luxury-2026",
  "/blog/wholesale-mortgage-broker-urban-seattle-premium-2026",
  "/blog/wholesale-mortgage-broker-western-la-luxury-2026",
  "/areas/laguna-beach-mortgage-broker",
  "/areas/newport-beach",
  "/blog/home-equity-affluent-suburban-east-bay-2026",
  "/blog/home-equity-ca-sd-a-2026",
  "/blog/home-equity-coastal-north-sd-2026",
  "/blog/home-equity-inland-empire-affluent-2026",
  "/blog/home-equity-la-beach-cities-2026",
  "/blog/home-equity-malibu-ca-2026",
  "/blog/home-equity-pacific-palisades-ca-2026",
  "/blog/home-equity-sacramento-affluent-2026",
  "/blog/home-equity-ventura-affluent-ca-2026",
  "/blog/home-equity-wine-country-2026",
  "/blog/home-equity-wine-country-guide-2026",
  "/blog/laguna-beach-mortgage-guide-2026",
  "/blog/reverse-mortgage-affluent-suburban-east-bay-2026",
  "/blog/reverse-mortgage-coastal-north-sd-2026",
  "/blog/reverse-mortgage-ie-affluent-2026",
  "/blog/reverse-mortgage-malibu-ca-2026",
  "/blog/reverse-mortgage-pacific-palisades-ca-2026",
  "/blog/reverse-mortgage-sacramento-affluent-2026",
  "/blog/reverse-mortgage-ventura-affluent-2026",
  "/blog/reverse-mortgage-wine-country-2026",
  "/blog/reverse-mortgage-wine-country-guide-2026",
  "/blog/wholesale-mortgage-92625-corona-del-mar-2026",
  "/blog/wholesale-mortgage-92629-dana-point-2026",
  "/blog/wholesale-mortgage-92651-laguna-beach-2026",
  "/blog/wholesale-mortgage-92660-newport-harbor-2026",
  "/blog/wholesale-mortgage-92661-newport-beach-2026",
  "/blog/wholesale-mortgage-broker-affluent-suburban-east-bay-2026",
  "/blog/wholesale-mortgage-broker-ca-sd-a-2026",
  "/blog/wholesale-mortgage-broker-ca-sgv-a-2026",
  "/blog/wholesale-mortgage-broker-coastal-north-sd-2026",
  "/blog/wholesale-mortgage-broker-la-beach-cities-2026",
  "/neighborhood-guide/newport-beach-vs-laguna-beach-home-buying-guide",
  "/zip-codes/92660-newport-beach-mortgage-broker",
  "/blog/coto-de-caza-mortgage-guide-2026",
  "/blog/home-equity-beverly-hills-2026",
  "/blog/home-equity-san-marino-ca-2026",
  "/blog/reverse-mortgage-beverly-hills-2026",
  "/blog/reverse-mortgage-san-marino-ca-2026",
  "/blog/wholesale-mortgage-92679-coto-de-caza-2026"
];
